---
#
# Installing Filebeat
#

# Install Filebeat 

- name: Install Filebeat
  yum:
   name: filebeat
   state: present

- name: Updating the config file to enable filebeat
  lineinfile:
   destfile: /etc/filebeat/filebeat.yml
   regexp: 'enabled:'
   line: 'enabled: true'

# Starting Filebeat

- name: Starting Filebeat
  service:
   name: filebeat
   state: started

- name: Enable service Filebeat
  service:
    name: filebeat
    enabled: yes
