---
#
# Installing Metricbeat
#

# Install Metricbeat 

- name: Install Metricbeat
  yum:
   name: metricbeat
   state: present


- name: Enable service Metricbeat
  service:
    name: metricbeat
    enabled: yes
 
# Starting Metricbeat

- name: Starting Metricbeat
  service:
   name: metricbeat
   state: started
